name: Build Ghostty for macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Zig
      run: |
        brew install zig

    - name: Build Ghostty
      run: |
        zig build -Doptimize=ReleaseFast

    - name: Build Mac App
      run: |
        cd macos && xcodebuild

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ghostty-macos
        path: macos/build/ReleaseLocal/Ghostty.app
